version: '3.9'

services:
  simpa:
    image: simpa
    environment:
      - NODE_ENV=development
      - SESSION_SECRET=secret
      - PASSWORD=demo
      - SIMPA_ADDRESS=https://localhost:8080
      - FILTER_ORIGIN=false
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SIMPA_ADDRESS=https://localhost:8080
    ports:
      - '8080:3000'

    volumes:
      - data:/home/node/data

volumes:
  data:
  src:
