version: '3.9'

services:
  simpa:
    image: simpa
    environment:
      - NODE_ENV=development
      - SESSION_SECRET=secret
      - PASSWORD=plop
      - SIMPA_ADDRESS=https://google.fr
      - FILTER_ORIGIN=false
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SIMPA_ADDRESS=https://google.fr
    ports:
      - '8080:3000'

    volumes:
      - data:/home/node/data

volumes:
  data:
  src:
