version: '3.9'

services:
  simpa:
    image: simpa
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - data:/home/node/data

volumes:
  data:
  src:
